# Generated by Django 3.1.6 on 2021-02-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('signal_source', models.CharField(max_length=50)),
                ('security_name', models.CharField(max_length=20)),
                ('decision', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
