# Generated by Django 3.1.6 on 2021-02-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
